version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  minio:
    image: minio/minio:latest
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=StrongPass123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s

  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    env_file:
      - ./.env 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  redis_data:
  minio_data:
