version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio:latest
    restart: always
    ports:
      - "9000:9000"  # API Port
      - "9001:9001"  # Web Console Port
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=StrongPass123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - minio
    env_file:
      - ./.env 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  redis_data:
  minio_data:
